name: api-prod

services:
    rest:
        build:
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - DATABASE_URL=${DATABASE_URL_LOCAL}
            - ENV=prod
        depends_on:
            db:
                condition: service_healthy
        networks:
            - backend
    db:
        build:
            dockerfile: Dockerfile.pg
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data_prod:/var/lib/postgresql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - backend

    ollama:
        image: ollama/ollama:latest
        ports:
            - "11434:11434"
        volumes:
            - ollama_data_prod:/root/.ollama
        entrypoint:
            [
                "/bin/sh",
                "-c",
                "ollama serve & sleep 5 && ollama pull leoipulsar/harrier-0.6b && wait",
            ]
        networks:
            - backend
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

volumes:
    postgres_data_prod:
    ollama_data_prod:

networks:
    backend:
        driver: bridge
