FROM rust:1.95.0

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/root/.cargo/bin \
    cargo install sea-orm-cli

RUN --mount=type=cache,target=/usr/local/rustup/downloads \
    rustup component add rustfmt

WORKDIR /app

RUN mkdir -p src/entities

CMD ["sh", "-c", "sea-orm-cli generate entity --database-url postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME} --output-dir src/entities --ignore-tables _prisma_migrations --ignore-tables _prisma_migrations_lock -v"]