FROM postgres:18-bookworm

RUN apt-get update

RUN apt-get install -y --no-install-recommends postgresql-18-pgvector

RUN apt-get install -y --no-install-recommends postgresql-18-postgis-3

RUN rm -rf /var/lib/apt/lists/*