FROM node:24-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN --mount=type=cache,target=/root/.npm npm ci --legacy-peer-deps

COPY prisma.config.ts ./

ENV ENV="prod"

COPY prisma ./prisma

CMD ["npm", "run", "db:deploy"]