FROM rust:1.95.0

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/root/.cargo/bin \
    cargo install cargo-watch

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN touch src/main.rs

ENV PORT=8080

EXPOSE 8080

CMD ["cargo", "watch", "-x", "run"]